# Generated by Django 4.0.1 on 2022-01-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-join_club_date']},
        ),
    ]
