# Generated by Django 4.0.1 on 2022-01-17 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='books_rented',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='shifts_per_week',
        ),
    ]
