# Generated by Django 4.0.1 on 2022-01-18 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='meet_date',
            field=models.DateField(default=datetime.date(2022, 1, 18), verbose_name='Meeting Date'),
        ),
    ]
