# Generated by Django 4.0.1 on 2022-01-19 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('image', models.CharField(max_length=200, null=True)),
                ('author_name', models.CharField(blank=True, max_length=200, null=True)),
                ('key', models.CharField(max_length=100, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('image', models.CharField(max_length=200, null=True)),
                ('author_name', models.CharField(blank=True, max_length=200, null=True)),
                ('key', models.CharField(max_length=100, null=True, unique=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='main_app.member')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
