# Generated by Django 4.0.1 on 2022-01-18 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_club_location_alter_club_meet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='club',
            name='meet_date',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
    ]
