# Generated by Django 4.0.1 on 2022-01-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_club_meet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='meet_date',
            field=models.DateField(),
        ),
    ]
